Flower fix
unicef/hope-country-report pull request #56
Opened 2024-08-02 12:09 UTC by srugano

2024-08-12 08:36 UTC, wozniakpl requested changes
The compose services do not start.

```
flower-1         |   File "/packages/__pypackages__/3.11/lib/azure/storage/blob/_blob_service_client.py", line 735, in get_container_client
flower-1         |     return ContainerClient(
flower-1         |            ^^^^^^^^^^^^^^^^
flower-1         |   File "/packages/__pypackages__/3.11/lib/azure/storage/blob/_container_client.py", line 158, in __init__
flower-1         |     raise ValueError("Please specify a container name.")
flower-1         | ValueError: Please specify a container name.
```

2024-08-20 10:27 UTC, srugano commented
> The compose services do not start.
> 
> ```
> flower-1         |   File "/packages/__pypackages__/3.11/lib/azure/storage/blob/_blob_service_client.py", line 735, in get_container_client
> flower-1         |     return ContainerClient(
> flower-1         |            ^^^^^^^^^^^^^^^^
> flower-1         |   File "/packages/__pypackages__/3.11/lib/azure/storage/blob/_container_client.py", line 158, in __init__
> flower-1         |     raise ValueError("Please specify a container name.")
> flower-1         | ValueError: Please specify a container name.
> ```

@wozniakpl  the default storage has been added. it should be Ok now.

2024-08-20 11:52 UTC, wozniakpl approved these changes

2024-08-20 11:53 UTC, wozniakpl commented
> > The compose services do not start.
> > ```
> > flower-1         |   File "/packages/__pypackages__/3.11/lib/azure/storage/blob/_blob_service_client.py", line 735, in get_container_client
> > flower-1         |     return ContainerClient(
> > flower-1         |            ^^^^^^^^^^^^^^^^
> > flower-1         |   File "/packages/__pypackages__/3.11/lib/azure/storage/blob/_container_client.py", line 158, in __init__
> > flower-1         |     raise ValueError("Please specify a container name.")
> > flower-1         | ValueError: Please specify a container name.
> > ```
> 
> @wozniakpl the default storage has been added. it should be Ok now.

I added 5555:5555 forwarding and I was able to visit the dashboard at localhost:5555. Thanks.

2024-08-20 12:33 UTC, merged